services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: codebase-rag
    ports:
      - "8501:8501"
    volumes:
      - .:/app
      - ./.env:/app/.env
    env_file:
      - .env
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
    restart: "no"
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G
    networks:
      - app_net

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"   # HTTP API
      - "6334:6334"   # gRPC API (optional)
    volumes:
      - qdrant_data:/qdrant/storage
    restart: "unless-stopped"
    networks:
      - app_net

volumes:
  qdrant_data:

networks:
  app_net:
    driver: bridge